{
  "openapi": "3.0.1",
  "info": {
    "title": "SLEEPOVER API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/hotels": {
      "get": {
        "summary": "Retrieves all hotels",
        "tags": [
          "Hotels"
        ],
        "description": "Retrieves all hotels (only logged in users or admin can retrieve hotels) by recieving token with the request that is sent as response body after login",
        "responses": {
          "200": {
            "description": "hotels retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "city": {
                        "type": "string"
                      },
                      "country": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "image": {
                        "type": "string"
                      },
                      "details": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "image",
                      "city",
                      "country",
                      "phone",
                      "details"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "summary": "Add new hotel",
        "tags": [
          "Hotels"
        ],
        "description": "Add new hotel (only logged in admin can add new hotel) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "hotel added"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Not created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "country": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "image",
                  "city",
                  "country",
                  "phone",
                  "details"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/reservations": {
      "get": {
        "summary": "Retrieves all Reservations",
        "tags": [
          "Reservations"
        ],
        "description": "Retrieves all reservations (only for the logged in user or admin can retrieve all his/her reservations) by recieving token with the request that is sent as response body after login",
        "responses": {
          "200": {
            "description": "reservations retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "room_id": {
                        "type": "integer"
                      },
                      "start_date": {
                        "type": "date"
                      },
                      "end_date": {
                        "type": "date"
                      },
                      "archived": {
                        "type": "boolean"
                      },
                      "user_id": {
                        "type": "integer"
                      },
                      "hotel_id": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "id",
                      "room_id",
                      "start_date",
                      "end_date",
                      "archived",
                      "user_id",
                      "hotel_id"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "summary": "Add new resrvation",
        "tags": [
          "Reservations"
        ],
        "description": "Add new resrvation (only logged in admin can add new resrvation) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "resrevation added"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Not created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "room_id": {
                    "type": "integer"
                  },
                  "start_date": {
                    "type": "date"
                  },
                  "end_date": {
                    "type": "date"
                  },
                  "archived": {
                    "type": "boolean"
                  },
                  "user_id": {
                    "type": "integer"
                  },
                  "hotel_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "id",
                  "room_id",
                  "start_date",
                  "end_date",
                  "archived",
                  "user_id",
                  "hotel_id"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/rooms": {
      "get": {
        "summary": "Retrieves all rooms",
        "tags": [
          "Rooms"
        ],
        "description": "Retrieves all rooms (only logged in users or admin can retrieve rooms) by recieving token with the request that is sent as response body after login",
        "responses": {
          "200": {
            "description": "rooms retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "room_no": {
                        "type": "integer"
                      },
                      "number_of_bed": {
                        "type": "integer"
                      },
                      "prices": {
                        "type": "decimal"
                      },
                      "photo": {
                        "type": "string"
                      },
                      "reserve": {
                        "type": "boolean"
                      },
                      "user_id": {
                        "type": "integer"
                      },
                      "hotel_id": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "id",
                      "room_no",
                      "number_of_bed",
                      "image",
                      "prices",
                      "photo",
                      "reserve",
                      "user_id",
                      "hotel_id"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "summary": "Add new room",
        "tags": [
          "Rooms"
        ],
        "description": "Add new room (only logged in admin can add new room) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "room added"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Not created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "room_no": {
                    "type": "integer"
                  },
                  "number_of_bed": {
                    "type": "integer"
                  },
                  "prices": {
                    "type": "decimal"
                  },
                  "photo": {
                    "type": "string"
                  },
                  "reserve": {
                    "type": "boolean"
                  },
                  "user_id": {
                    "type": "integer"
                  },
                  "hotel_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "id",
                  "room_no",
                  "number_of_bed",
                  "image",
                  "prices",
                  "photo",
                  "reserve",
                  "user_id",
                  "hotel_id"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/signup": {
      "post": {
        "summary": "Add new user",
        "tags": [
          "Users"
        ],
        "description": "Add new user. one parameter can be added in a direct request to the api this could contain 'role' and this is the way to add admin.",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "success"
          },
          "422": {
            "description": "password cannot be blank"
          },
          "400": {
            "description": "bad request, you are already registered"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "username",
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "summary": "login",
        "tags": [
          "Users"
        ],
        "description": "Log user in. This request will return such object: \n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t'token': <token_string>,\n\t\t\t\t\t\t\t'user': { 'username': <username_string>, 'role': 'role_string' }\n\t\t\t\t\t\t}. \n\t\t\t\t\t\t",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "success"
          },
          "422": {
            "description": "email cannot be blank"
          },
          "400": {
            "description": "bad request wrong password or email"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000"
        }
      }
    }
  ]
}