{
  "openapi": "3.0.1",
  "info": {
    "title": "SLEEPOVER API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/hotels": {
      "get": {
        "summary": "Retrieves all hotels",
        "tags": [
          "Hotels"
        ],
        "description": "Retrieves all hotels (only logged in users or admin can retrieve hotels) by recieving token with the request that is sent as response body after login",
        "responses": {
          "200": {
            "description": "hotels retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "name": {
                        "type": "string"
                      },
                      "city": {
                        "type": "string"
                      },
                      "country": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "image": {
                        "type": "string"
                      },
                      "details": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "image",
                      "city",
                      "country",
                      "phone",
                      "details"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "summary": "Add new hotel",
        "tags": [
          "Hotels"
        ],
        "description": "Add new hotel (only logged in admin can add new hotel) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "hotel added"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Not created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "city": {
                    "type": "string"
                  },
                  "country": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  },
                  "details": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "image",
                  "city",
                  "country",
                  "phone",
                  "details"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/hotels/{id}/rooms": {
      "get": {
        "summary": "Retrieves all rooms",
        "tags": [
          "Rooms"
        ],
        "description": "Retrieves all rooms (only logged in users or admin can retrieve rooms) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "rooms retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "room_no": {
                        "type": "integer"
                      },
                      "number_of_bed": {
                        "type": "integer"
                      },
                      "prices": {
                        "type": "decimal"
                      },
                      "photo": {
                        "type": "string"
                      },
                      "reserve": {
                        "type": "boolean"
                      },
                      "user_id": {
                        "type": "integer"
                      },
                      "hotel_id": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "id",
                      "room_no",
                      "number_of_bed",
                      "image",
                      "prices",
                      "photo",
                      "reserve",
                      "user_id",
                      "hotel_id"
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/v1/rooms": {
      "post": {
        "summary": "Add new room",
        "tags": [
          "Rooms"
        ],
        "description": "Add new room (only logged in admin can add new room) by recieving token with the request that is sent as response body after login",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "room added"
          },
          "401": {
            "description": "Unauthorized"
          },
          "422": {
            "description": "Not created"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "room_no": {
                    "type": "integer"
                  },
                  "number_of_bed": {
                    "type": "integer"
                  },
                  "prices": {
                    "type": "decimal"
                  },
                  "photo": {
                    "type": "string"
                  },
                  "reserve": {
                    "type": "boolean"
                  },
                  "user_id": {
                    "type": "integer"
                  },
                  "hotel_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "id",
                  "room_no",
                  "number_of_bed",
                  "image",
                  "prices",
                  "photo",
                  "reserve",
                  "user_id",
                  "hotel_id"
                ]
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000"
        }
      }
    }
  ]
}