default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_dev

  # adapter: postgresql
  # encoding: unicode
  # port: 5432
  # host : localhost
  # username: postgres
  # password: 12@34

test:
  <<: *default
  database: hotel_test 
  # host : localhost
  # port: 5432
  # adapter: postgresql
  # encoding: unicode
  # username: postgres
  # password: 12@34


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
