default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_dev
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: benkis
  port: 5432

test:
  <<: *default
  database: hotel_test
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: benkis
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
